name: ci

on: [push]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: |
        docker build . -t drecoppers/frontendpebs2:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAAM_FRONT }}
        password: ${{ secrets.DOCKER_PASS_FRONT }}

    - name: Docker push
      run: |
        docker push drecoppers/frontendpebs2
